name: duplicator
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pip:
    - pyinstaller>=5.6.2
    - pillow>=9.0.0  # Required for icon creation 